server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  application:
    name: springbootdemo-actuator
  security:
      user:
        name: johann
        password: 911

management:
  # 端点信息接口使用的端口，为了和主系统接口使用的端口进行分离
  server:
    port: 8090
    servlet:
      context-path: /act
  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: ALWAYS
    # 通过指定接口关闭 SpringBoot
    shutdown:
      enabled: true
    # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: "health,info,env,beans,shutdown"
        #include: "*"
      # 自定义监控路径 monitor。默认 /actuator
      base-path: /monitor

# 描述项目基础信息
info:
  app:
    name: sptingbootdemo-actuator
    port: 8090
    version: 1.0.0
    author: johann